version: '3.8'
services:
  backend:
    container_name: pet_laravel
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_DATABASE: 'pet-laravel-db'
      DB_USERNAME: admin
      DB_PASSWORD: admin
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app
  phpMyAdmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - 8080:80
    networks:
      - app
  db:
    container_name: pet_laravel_db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'pet-laravel-db'
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - app
networks:
  app:
